### ISSUE TITLE
Non-static method Skraeda\AutoMapper\AutoMapper::getConfiguration() should not be called statically

### ISSUE THREAD

**Issue by zozidalom** [Skraeda/laravel-automapper#3]
Hi, I am facing the following issue when trying to set up the automapper for laravel 8.x.

![image](https://user-images.githubusercontent.com/24374345/105615179-e9ace380-5dce-11eb-9456-8c75e0afab0d.png)

Can you please help me to resolve this?

**Comment by zozidalom** [comment]
@Gunsobal

**Comment by Gunsobal** [comment]
@zozidalom You need to use the Facade or resolved AutoMapper instance to access the mapping config instead of calling \Skraeda\AutoMapper\AutoMapper directly. 

Try

```php
use Skraeda\AutoMapper\Support\Facades\AutoMapperFacade as AutoMapper;
```
instead of

```php
use Skraeda\AutoMapper\AutoMapper;
```

**Comment by zozidalom** [comment]
Works, thank you!
